name: Deploy Bicep Infrastructure

env:
    resourceGroupName : fileupdownloder-rg

on:
  push:
    branches:
      - main
    paths:
      - 'deply/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep template with parameter file
        run: |
          az deployment group create \
            --resource-group ${{ env.resourceGroupName }} \
            --template-file deply/azuredeploy.bicep
