# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
# アプリ登録は必須

name: Build and deploy Python app to Azure Web App

env:
    resourceGroupName : ${{ vars.RESOURCE_GROUP_NAME }}
    isAuth : false # Microsoft Entra ID Auth

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write #This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Azure Login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Bicep テンプレートをデプロイし、outputs から webAppName と storageAccountName を取得
      - name: Deploy Bicep template
        id: deploy_bicep
        run: |
          az deployment group create \
            --resource-group ${{ env.resourceGroupName }} \
            --template-file deploy/azuredeploy.bicep \
            --parameters webAppName=${{ vars.WEB_APP_NAME }} storageAccountNamePrefix=${{ vars.STORAGE_ACCOUNT_NAME_PREFIX }} storageAccountContainer=${{ vars.STORAGE_ACCOUNT_CONTAINER }} 
          
      # Azure Web Apps にデプロイ
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ vars.WEB_APP_NAME }}
          slot-name: 'Production'

      # 環境変数を設定
      - name: 'Set environment variables'
        run: |
          az webapp config appsettings set --name ${{ vars.WEB_APP_NAME }} --resource-group ${{ env.resourceGroupName }} --settings \
            DISABLE_AUTH=${{ env.isAuth }} \
            REDIRECT_URI=${{ vars.REDIRECT_URI }} \
            FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} \
            CLIENT_ID=${{ secrets.CLIENT_ID }} \
            TENANT_ID=${{ secrets.TENANT_ID }} \
            CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
